# ilo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ilo-credentials
  namespace: seeder-system
type: Opaque
stringData:
  username: "###ZARF_VAR_ILO_USERNAME###"
  password: "###ZARF_VAR_ILO_PASSWORD###"